val (+) : Stlc.gremVal -> Stlc.gremVal -> Stlc.gremVal
val (-) : Stlc.gremVal -> Stlc.gremVal -> Stlc.gremVal
val (+*) : Stlc.gremVal -> Stlc.gremVal -> Stlc.gremVal
val (/) : Stlc.gremVal -> Stlc.gremVal -> Stlc.gremVal
val (>) : Stlc.gremVal -> Stlc.gremVal -> Stlc.gremVal
val (>=) : Stlc.gremVal -> Stlc.gremVal -> Stlc.gremVal
val (<) : Stlc.gremVal -> Stlc.gremVal -> Stlc.gremVal
val (<=) : Stlc.gremVal -> Stlc.gremVal -> Stlc.gremVal
val (=) : Stlc.gremVal -> Stlc.gremVal -> Stlc.gremVal
val (<>) : Stlc.gremVal -> Stlc.gremVal -> Stlc.gremVal
